include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
    - "**/generated/**"
    - "build/**"

linter:
  rules:
    - prefer_single_quotes
    - always_declare_return_types
    - directives_ordering
    - unawaited_futures
